browserConfig:
  driverEnum: CHROME

environment:
  prod:
    appUrl: http://146.59.32.4
    active: true
    max_value_first_filter: $10.00
    min_value_first_filter: $9.00
    min_value_second_filter: $9.00
    max_value_second_filter: $25.00
  init:
    appUrl: http://146.59.32.4
    active: false
    max_value_first_filter: $10.00
    min_value_first_filter: $9.00
    min_value_second_filter: $10.00
    max_value_second_filter: $29.00






